// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_api_v1_auth_login_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login_api_v1_auth_login_post'
} as const;

export const Body_upload_document_api_v1_documents_upload_postSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File',
            description: 'PDF file to upload (max 50 MB)'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_upload_document_api_v1_documents_upload_post'
} as const;

export const CitationOutSchema = {
    properties: {
        alias: {
            type: 'string',
            title: 'Alias'
        },
        chunk_id: {
            type: 'string',
            title: 'Chunk Id'
        },
        document_id: {
            type: 'string',
            title: 'Document Id'
        },
        source_filename: {
            type: 'string',
            title: 'Source Filename'
        },
        page_number: {
            type: 'integer',
            title: 'Page Number'
        },
        section_title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Section Title'
        },
        snippet: {
            type: 'string',
            title: 'Snippet'
        }
    },
    type: 'object',
    required: ['alias', 'chunk_id', 'document_id', 'source_filename', 'page_number', 'section_title', 'snippet'],
    title: 'CitationOut'
} as const;

export const ConversationCreateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    title: 'ConversationCreate'
} as const;

export const ConversationListResponseSchema = {
    properties: {
        conversations: {
            items: {
                '$ref': '#/components/schemas/ConversationPublic'
            },
            type: 'array',
            title: 'Conversations'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['conversations', 'total'],
    title: 'ConversationListResponse'
} as const;

export const ConversationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    required: ['id', 'tenant_id', 'user_id', 'title'],
    title: 'ConversationPublic'
} as const;

export const DocumentListResponseSchema = {
    properties: {
        documents: {
            items: {
                '$ref': '#/components/schemas/DocumentPublic'
            },
            type: 'array',
            title: 'Documents'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['documents', 'total'],
    title: 'DocumentListResponse'
} as const;

export const DocumentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        },
        original_filename: {
            type: 'string',
            title: 'Original Filename'
        },
        status: {
            '$ref': '#/components/schemas/DocumentStatus'
        },
        page_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Count'
        },
        file_size_bytes: {
            type: 'integer',
            title: 'File Size Bytes'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        uploaded_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Uploaded By Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'tenant_id', 'original_filename', 'status', 'page_count', 'file_size_bytes', 'error_message', 'uploaded_by_id'],
    title: 'DocumentPublic'
} as const;

export const DocumentStatusSchema = {
    type: 'string',
    enum: ['pending', 'processing', 'ready', 'failed'],
    title: 'DocumentStatus'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageListResponseSchema = {
    properties: {
        messages: {
            items: {
                '$ref': '#/components/schemas/MessagePublic'
            },
            type: 'array',
            title: 'Messages'
        },
        total: {
            type: 'integer',
            title: 'Total'
        }
    },
    type: 'object',
    required: ['messages', 'total'],
    title: 'MessageListResponse'
} as const;

export const MessagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        citations_json: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Citations Json'
        }
    },
    type: 'object',
    required: ['id', 'conversation_id', 'role', 'content', 'citations_json'],
    title: 'MessagePublic'
} as const;

export const PresignedUrlResponseSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        expires_in_seconds: {
            type: 'integer',
            title: 'Expires In Seconds'
        }
    },
    type: 'object',
    required: ['url', 'expires_in_seconds'],
    title: 'PresignedUrlResponse'
} as const;

export const QueryRequestSchema = {
    properties: {
        question: {
            type: 'string',
            title: 'Question'
        },
        document_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Ids'
        }
    },
    type: 'object',
    required: ['question'],
    title: 'QueryRequest'
} as const;

export const QueryResponseSchema = {
    properties: {
        conversation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Conversation Id'
        },
        answer: {
            type: 'string',
            title: 'Answer'
        },
        citations: {
            items: {
                '$ref': '#/components/schemas/CitationOut'
            },
            type: 'array',
            title: 'Citations'
        },
        chunks_used: {
            type: 'integer',
            title: 'Chunks Used'
        },
        model_used: {
            type: 'string',
            title: 'Model Used'
        }
    },
    type: 'object',
    required: ['conversation_id', 'answer', 'citations', 'chunks_used', 'model_used'],
    title: 'QueryResponse'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        user: {
            '$ref': '#/components/schemas/UserPublic'
        }
    },
    type: 'object',
    required: ['access_token', 'user'],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tenant_id: {
            type: 'string',
            format: 'uuid',
            title: 'Tenant Id'
        }
    },
    type: 'object',
    required: ['email', 'id', 'tenant_id'],
    title: 'UserPublic',
    description: 'Safe response schema — never exposes hashed_password.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            title: 'Email'
        },
        password: {
            type: 'string',
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Input from the registration endpoint.'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Fields a user can update on their own profile (no privilege escalation).'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;