// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginApiV1AuthLoginPostData, LoginApiV1AuthLoginPostResponse, RegisterApiV1AuthRegisterPostData, RegisterApiV1AuthRegisterPostResponse, CreateConversationApiV1ChatConversationsPostData, CreateConversationApiV1ChatConversationsPostResponse, ListConversationsApiV1ChatConversationsGetData, ListConversationsApiV1ChatConversationsGetResponse, GetMessagesApiV1ChatConversationsConversationIdMessagesGetData, GetMessagesApiV1ChatConversationsConversationIdMessagesGetResponse, QueryConversationApiV1ChatConversationsConversationIdQueryPostData, QueryConversationApiV1ChatConversationsConversationIdQueryPostResponse, UploadDocumentApiV1DocumentsUploadPostData, UploadDocumentApiV1DocumentsUploadPostResponse, ListDocumentsApiV1DocumentsGetData, ListDocumentsApiV1DocumentsGetResponse, GetDocumentApiV1DocumentsDocumentIdGetData, GetDocumentApiV1DocumentsDocumentIdGetResponse, DeleteDocumentApiV1DocumentsDocumentIdDeleteData, DeleteDocumentApiV1DocumentsDocumentIdDeleteResponse, GetDocumentUrlApiV1DocumentsDocumentIdUrlGetData, GetDocumentUrlApiV1DocumentsDocumentIdUrlGetResponse, ProxyDocumentStreamApiV1DocumentsDocumentIdProxyGetData, ProxyDocumentStreamApiV1DocumentsDocumentIdProxyGetResponse, HealthCheckApiV1HealthGetResponse, ReadCurrentUserApiV1UsersMeGetResponse, UpdateCurrentUserApiV1UsersMePatchData, UpdateCurrentUserApiV1UsersMePatchResponse } from './types.gen';

export class AuthService {
    /**
     * Login
     * Authenticate with email + password, receive a JWT.
     *
     * Uses OAuth2PasswordRequestForm so the OpenAPI /docs "Authorize" button works.
     * The `username` field in the form is treated as the user's email address.
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginApiV1AuthLoginPost(data: LoginApiV1AuthLoginPostData): CancelablePromise<LoginApiV1AuthLoginPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/login',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Register
     * Register a new account.
     *
     * Creates:
     * 1. A Tenant (isolated workspace named after the user)
     * 2. A User linked to that Tenant
     *
     * The JWT returned contains both user.id and tenant.id so every
     * subsequent request is automatically scoped to the correct tenant.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static registerApiV1AuthRegisterPost(data: RegisterApiV1AuthRegisterPostData): CancelablePromise<RegisterApiV1AuthRegisterPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/auth/register',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ChatService {
    /**
     * Start a new conversation
     * Create a blank conversation context for follow-up queries.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ConversationPublic Successful Response
     * @throws ApiError
     */
    public static createConversationApiV1ChatConversationsPost(data: CreateConversationApiV1ChatConversationsPostData): CancelablePromise<CreateConversationApiV1ChatConversationsPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chat/conversations',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * List all conversations for the current user
     * Return a paginated list of the user's past conversations.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ConversationListResponse Successful Response
     * @throws ApiError
     */
    public static listConversationsApiV1ChatConversationsGet(data: ListConversationsApiV1ChatConversationsGetData = {}): CancelablePromise<ListConversationsApiV1ChatConversationsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/chat/conversations',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Get full message history for a conversation
     * Return all messages in a conversation, oldest-first.
     * @param data The data for the request.
     * @param data.conversationId
     * @returns MessageListResponse Successful Response
     * @throws ApiError
     */
    public static getMessagesApiV1ChatConversationsConversationIdMessagesGet(data: GetMessagesApiV1ChatConversationsConversationIdMessagesGetData): CancelablePromise<GetMessagesApiV1ChatConversationsConversationIdMessagesGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/chat/conversations/{conversation_id}/messages',
            path: {
                conversation_id: data.conversationId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Ask a question and receive a cited answer
     * Runs the full RAG pipeline: embed query → hybrid retrieve → RRF fuse → LLM generate → parse citations → persist messages. The response answer text contains inline [Doc N] citation markers which are resolved into structured citation objects in the `citations` array.
     * @param data The data for the request.
     * @param data.conversationId
     * @param data.requestBody
     * @returns QueryResponse Successful Response
     * @throws ApiError
     */
    public static queryConversationApiV1ChatConversationsConversationIdQueryPost(data: QueryConversationApiV1ChatConversationsConversationIdQueryPostData): CancelablePromise<QueryConversationApiV1ChatConversationsConversationIdQueryPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/chat/conversations/{conversation_id}/query',
            path: {
                conversation_id: data.conversationId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class DocumentsService {
    /**
     * Upload a PDF contract
     * Upload a PDF file (max 50 MB). The file is stored in MinIO, a Document record is created with status=`pending`, and a background ingestion task is dispatched to Celery (Phase 3 pipeline).
     * @param data The data for the request.
     * @param data.formData
     * @returns DocumentPublic Successful Response
     * @throws ApiError
     */
    public static uploadDocumentApiV1DocumentsUploadPost(data: UploadDocumentApiV1DocumentsUploadPostData): CancelablePromise<UploadDocumentApiV1DocumentsUploadPostResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/documents/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * List all documents for the current tenant
     * Return a paginated list of documents uploaded by the current tenant.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns DocumentListResponse Successful Response
     * @throws ApiError
     */
    public static listDocumentsApiV1DocumentsGet(data: ListDocumentsApiV1DocumentsGetData = {}): CancelablePromise<ListDocumentsApiV1DocumentsGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/documents',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Get document metadata
     * Fetch metadata for a single document (tenant-scoped).
     * @param data The data for the request.
     * @param data.documentId
     * @returns DocumentPublic Successful Response
     * @throws ApiError
     */
    public static getDocumentApiV1DocumentsDocumentIdGet(data: GetDocumentApiV1DocumentsDocumentIdGetData): CancelablePromise<GetDocumentApiV1DocumentsDocumentIdGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/documents/{document_id}',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Hard-delete a document
     * Permanently deletes the PDF from MinIO and removes the Document record (and all associated chunks via CASCADE) from the database. This action is irreversible.
     * @param data The data for the request.
     * @param data.documentId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static deleteDocumentApiV1DocumentsDocumentIdDelete(data: DeleteDocumentApiV1DocumentsDocumentIdDeleteData): CancelablePromise<DeleteDocumentApiV1DocumentsDocumentIdDeleteResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/documents/{document_id}',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Get a pre-signed download URL for the PDF
     * Returns a time-limited URL (default 1 hour) that the frontend can use to stream the PDF directly from MinIO without routing through FastAPI. The document must belong to the requesting tenant.
     * @param data The data for the request.
     * @param data.documentId
     * @param data.expiresIn
     * @returns PresignedUrlResponse Successful Response
     * @throws ApiError
     */
    public static getDocumentUrlApiV1DocumentsDocumentIdUrlGet(data: GetDocumentUrlApiV1DocumentsDocumentIdUrlGetData): CancelablePromise<GetDocumentUrlApiV1DocumentsDocumentIdUrlGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/documents/{document_id}/url',
            path: {
                document_id: data.documentId
            },
            query: {
                expires_in: data.expiresIn
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Proxy stream for document (CORS-safe)
     * Streams the PDF through the backend to avoid CORS issues in local dev.
     * @param data The data for the request.
     * @param data.documentId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static proxyDocumentStreamApiV1DocumentsDocumentIdProxyGet(data: ProxyDocumentStreamApiV1DocumentsDocumentIdProxyGetData): CancelablePromise<ProxyDocumentStreamApiV1DocumentsDocumentIdProxyGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/documents/{document_id}/proxy',
            path: {
                document_id: data.documentId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class HealthService {
    /**
     * Health check
     * Returns service health and database connectivity status.
     *
     * Used by Docker Compose healthcheck:
     * test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static checkApiV1HealthGet(): CancelablePromise<HealthCheckApiV1HealthGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/health'
        });
    }
}

export class UsersService {
    /**
     * Read Current User
     * Return the currently authenticated user's profile.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readCurrentUserApiV1UsersMeGet(): CancelablePromise<ReadCurrentUserApiV1UsersMeGetResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }

    /**
     * Update Current User
     * Update the current user's own profile (name only).
     *
     * Users cannot change their own email, password, or superuser status
     * through this endpoint — those require dedicated endpoints.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateCurrentUserApiV1UsersMePatch(data: UpdateCurrentUserApiV1UsersMePatchData): CancelablePromise<UpdateCurrentUserApiV1UsersMePatchResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}
