// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_api_v1_auth_login_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_upload_document_api_v1_documents_upload_post = {
    /**
     * PDF file to upload (max 50 MB)
     */
    file: (Blob | File);
};

export type CitationOut = {
    alias: string;
    chunk_id: string;
    document_id: string;
    source_filename: string;
    page_number: number;
    section_title: (string | null);
    snippet: string;
};

export type ConversationCreate = {
    title?: (string | null);
};

export type ConversationListResponse = {
    conversations: Array<ConversationPublic>;
    total: number;
};

export type ConversationPublic = {
    id: string;
    tenant_id: string;
    user_id: string;
    title: (string | null);
};

export type DocumentListResponse = {
    documents: Array<DocumentPublic>;
    total: number;
};

export type DocumentPublic = {
    id: string;
    tenant_id: string;
    original_filename: string;
    status: DocumentStatus;
    page_count: (number | null);
    file_size_bytes: number;
    error_message: (string | null);
    uploaded_by_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type DocumentStatus = 'pending' | 'processing' | 'ready' | 'failed';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MessageListResponse = {
    messages: Array<MessagePublic>;
    total: number;
};

export type MessagePublic = {
    id: string;
    conversation_id: string;
    role: string;
    content: string;
    citations_json: (string | null);
};

export type PresignedUrlResponse = {
    url: string;
    expires_in_seconds: number;
};

export type QueryRequest = {
    question: string;
    document_ids?: (Array<(string)> | null);
};

export type QueryResponse = {
    conversation_id: string;
    answer: string;
    citations: Array<CitationOut>;
    chunks_used: number;
    model_used: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
    user: UserPublic;
};

/**
 * Safe response schema — never exposes hashed_password.
 */
export type UserPublic = {
    email: string;
    full_name?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    id: string;
    tenant_id: string;
};

/**
 * Input from the registration endpoint.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Fields a user can update on their own profile (no privilege escalation).
 */
export type UserUpdateMe = {
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginApiV1AuthLoginPostData = {
    formData: Body_login_api_v1_auth_login_post;
};

export type LoginApiV1AuthLoginPostResponse = (Token);

export type RegisterApiV1AuthRegisterPostData = {
    requestBody: UserRegister;
};

export type RegisterApiV1AuthRegisterPostResponse = (Token);

export type CreateConversationApiV1ChatConversationsPostData = {
    requestBody: ConversationCreate;
};

export type CreateConversationApiV1ChatConversationsPostResponse = (ConversationPublic);

export type ListConversationsApiV1ChatConversationsGetData = {
    limit?: number;
    skip?: number;
};

export type ListConversationsApiV1ChatConversationsGetResponse = (ConversationListResponse);

export type GetMessagesApiV1ChatConversationsConversationIdMessagesGetData = {
    conversationId: string;
};

export type GetMessagesApiV1ChatConversationsConversationIdMessagesGetResponse = (MessageListResponse);

export type QueryConversationApiV1ChatConversationsConversationIdQueryPostData = {
    conversationId: string;
    requestBody: QueryRequest;
};

export type QueryConversationApiV1ChatConversationsConversationIdQueryPostResponse = (QueryResponse);

export type UploadDocumentApiV1DocumentsUploadPostData = {
    formData: Body_upload_document_api_v1_documents_upload_post;
};

export type UploadDocumentApiV1DocumentsUploadPostResponse = (DocumentPublic);

export type ListDocumentsApiV1DocumentsGetData = {
    limit?: number;
    skip?: number;
};

export type ListDocumentsApiV1DocumentsGetResponse = (DocumentListResponse);

export type GetDocumentApiV1DocumentsDocumentIdGetData = {
    documentId: string;
};

export type GetDocumentApiV1DocumentsDocumentIdGetResponse = (DocumentPublic);

export type DeleteDocumentApiV1DocumentsDocumentIdDeleteData = {
    documentId: string;
};

export type DeleteDocumentApiV1DocumentsDocumentIdDeleteResponse = (void);

export type GetDocumentUrlApiV1DocumentsDocumentIdUrlGetData = {
    documentId: string;
    expiresIn?: number;
};

export type GetDocumentUrlApiV1DocumentsDocumentIdUrlGetResponse = (PresignedUrlResponse);

export type ProxyDocumentStreamApiV1DocumentsDocumentIdProxyGetData = {
    documentId: string;
};

export type ProxyDocumentStreamApiV1DocumentsDocumentIdProxyGetResponse = (unknown);

export type HealthCheckApiV1HealthGetResponse = ({
    [key: string]: unknown;
});

export type ReadCurrentUserApiV1UsersMeGetResponse = (UserPublic);

export type UpdateCurrentUserApiV1UsersMePatchData = {
    requestBody: UserUpdateMe;
};

export type UpdateCurrentUserApiV1UsersMePatchResponse = (UserPublic);